Repository codefori/vscode-db2i, pull requests merged in 2024-03, with the labels that each got.

#209 Always turn cancel button off when a query is done
  src/views/results/resultSetPanelProvider.ts
Labels: bug

#215 Fix resultSet view not grabing focus after reconnection
  src/views/results/resultSetPanelProvider.ts
Labels: bug

#216 Fix CL statements over multiple lines
  src/views/results/index.ts
Labels: ready

#214 Add SelfIleStackFrame and InitialStackData interfaces for SELF
  src/config.ts
  src/extension.ts
  src/views/examples/exampleBrowser.ts
  src/views/jobManager/jobManagerView.ts
  src/views/jobManager/selfCodes/nodes.ts
  src/views/jobManager/selfCodes/selfCodesResultsView.ts
Labels: bug, ready

#212 List query history by date
  package.json
  src/Storage.ts
  src/config.ts
  src/views/queryHistoryView.ts
Labels: enhancement, ready

#217 Add footer to results table so status is always visible
  src/views/html.ts
  src/views/results/html.ts
Labels: enhancement, ready

#208 Feature/parameters
  global.d.ts
  src/database/callable.ts
  src/language/index.ts
  src/language/providers/callable.ts
  src/language/providers/completion.ts
  src/language/providers/completionItemCache.ts
  src/language/providers/completionProvider.ts
  src/language/providers/parameterProvider.ts
  src/language/sql/statement.ts
  src/language/sql/tests/statements.test.ts
  src/language/sql/tokens.ts
  src/language/sql/types.ts
Labels: ready
